#!/usr/bin/python
# EASY-INSTALL-ENTRY-SCRIPT: 'git-issues==0.0.0','console_scripts','git-issues'
__requires__ = 'git-issues==0.0.0'
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.exit(
        load_entry_point('git-issues==0.0.0', 'console_scripts', 'git-issues')()
    )
